### ISSUE TITLE
Remove user credentials

### ISSUE THREAD

**Issue by jarifibrahim** [kishansagathiya/shellscripts-for-keycloak-apis#1]
All the scripts in this repo contain actual username and password. You should never put user credentials on a public repository.

**Comment by kishansagathiya** [comment]
@jarifibrahim It's my personal keycloak instance. It is for my personal testing. We dont really care about whether user credentials are public or not, it is obvious given their values

**Comment by jarifibrahim** [comment]
@kishansagathiya Storing login credentials on a public repo is never a good idea. Even if it's your personal instance, you don't want random people to be able to log in.
